AR = ['/usr/bin/ar']
ARFLAGS = ['rcs']
BINDIR = '/home/thiongane/Documents/latticetester/installPlace/bin'
CC = ['/usr/bin/gcc']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('12', '2', '1')
CFLAGS = ['-std=c99', '-Wall']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_cshlib = ['-fPIC']
COMPILER_CC = 'gcc'
COMPILER_CXX = 'g++'
CPPPATH_ST = '-I%s'
CXX = ['/usr/bin/g++']
CXXFLAGS = ['-std=c++14', '-Wall', '-Wno-unused-local-typedefs', '-Wno-unused-function', '-Wnon-virtual-dtor']
CXXFLAGS_MACBUNDLE = ['-fPIC']
CXXFLAGS_cxxshlib = ['-fPIC']
CXXLNK_SRC_F = []
CXXLNK_TGT_F = ['-o']
CXX_NAME = 'gcc'
CXX_SRC_F = []
CXX_TGT_F = ['-c', '-o']
DATADIR = '/home/thiongane/Documents/latticetester/installPlace/share'
DATAROOTDIR = '/home/thiongane/Documents/latticetester/installPlace/share'
DEFINES = ['HAVE_NTL_VECTOR_H=1', 'HAVE_GMP_H=1', 'LATTICETESTER_VERSION="unknown"']
DEFINES_ST = '-D%s'
DEFINE_COMMENTS = {'HAVE_NTL_VECTOR_H': '', 'HAVE_GMP_H': '', 'LATTICETESTER_VERSION': ''}
DEST_BINFMT = 'elf'
DEST_CPU = 'x86_64'
DEST_OS = 'linux'
DOCDIR = '/home/thiongane/Documents/latticetester/installPlace/share/doc/'
DVIDIR = '/home/thiongane/Documents/latticetester/installPlace/share/doc/'
EXEC_PREFIX = '/home/thiongane/Documents/latticetester/installPlace'
HAVE_GMP_H = 1
HAVE_NTL_VECTOR_H = 1
HTMLDIR = '/home/thiongane/Documents/latticetester/installPlace/share/doc/'
INCLUDEDIR = '/home/thiongane/Documents/latticetester/installPlace/include'
INFODIR = '/home/thiongane/Documents/latticetester/installPlace/share/info'
LIBDIR = '/home/thiongane/Documents/latticetester/installPlace/lib64'
LIBEXECDIR = '/home/thiongane/Documents/latticetester/installPlace/libexec'
LIBPATH_ST = '-L%s'
LIB_GMP = ['gmp']
LIB_NTL = ['ntl']
LIB_ST = '-l%s'
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINKFLAGS_cxxshlib = ['-shared']
LINKFLAGS_cxxstlib = ['-Wl,-Bstatic']
LINK_CC = ['/usr/bin/gcc']
LINK_CXX = ['/usr/bin/g++']
LOCALEDIR = '/home/thiongane/Documents/latticetester/installPlace/share/locale'
LOCALSTATEDIR = '/home/thiongane/Documents/latticetester/installPlace/var'
MANDIR = '/home/thiongane/Documents/latticetester/installPlace/share/man'
OLDINCLUDEDIR = '/usr/include'
PACKAGE = []
PDFDIR = '/home/thiongane/Documents/latticetester/installPlace/share/doc/'
PREFIX = '/home/thiongane/Documents/latticetester/installPlace'
PSDIR = '/home/thiongane/Documents/latticetester/installPlace/share/doc/'
RPATH_ST = '-Wl,-rpath,%s'
SBINDIR = '/home/thiongane/Documents/latticetester/installPlace/sbin'
SHAREDSTATEDIR = '/home/thiongane/Documents/latticetester/installPlace/com'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
SYSCONFDIR = '/home/thiongane/Documents/latticetester/installPlace/etc'
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.so'
cstlib_PATTERN = 'lib%s.a'
cxxprogram_PATTERN = '%s'
cxxshlib_PATTERN = 'lib%s.so'
cxxstlib_PATTERN = 'lib%s.a'
define_key = ['HAVE_NTL_VECTOR_H', 'HAVE_GMP_H', 'LATTICETESTER_VERSION']
macbundle_PATTERN = '%s.bundle'
