AR = ['/usr/bin/ar']
ARFLAGS = ['rcs']
BINDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/bin'
BUILD_DOCS = True
CC = ['/usr/bin/gcc']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('11', '3', '0')
CFLAGS = ['-std=c99', '-Wall']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_cshlib = ['-fPIC']
COMPILER_CC = 'gcc'
COMPILER_CXX = 'g++'
CPPPATH_ST = '-I%s'
CXX = ['/usr/bin/g++']
CXXFLAGS = ['-std=c++14', '-Wall', '-Wno-unused-local-typedefs', '-Wno-unused-function', '-Wnon-virtual-dtor']
CXXFLAGS_MACBUNDLE = ['-fPIC']
CXXFLAGS_cxxshlib = ['-fPIC']
CXXLNK_SRC_F = []
CXXLNK_TGT_F = ['-o']
CXX_NAME = 'gcc'
CXX_SRC_F = []
CXX_TGT_F = ['-c', '-o']
DATADIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/share'
DATAROOTDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/share'
DEFINES = ['HAVE_NTL_VECTOR_H=1', 'HAVE_GMP_H=1', 'LATTICETESTER_VERSION="0.1.0-185"']
DEFINES_ST = '-D%s'
DEFINE_COMMENTS = {'HAVE_NTL_VECTOR_H': '', 'HAVE_GMP_H': '', 'LATTICETESTER_VERSION': ''}
DEST_BINFMT = 'elf'
DEST_CPU = 'x86_64'
DEST_OS = 'linux'
DOCDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/share/doc/'
DOXYGEN = ['/usr/bin/doxygen']
DVIDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/share/doc/'
EXEC_PREFIX = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace'
HAVE_GMP_H = 1
HAVE_NTL_VECTOR_H = 1
HTMLDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/share/doc/'
INCLUDEDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/include'
INCLUDES_TEST = ['examples']
INFODIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/share/info'
LATTICETESTER_VERSION = ['0.1.0-185']
LIBDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/lib64'
LIBEXECDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/libexec'
LIBPATH_ST = '-L%s'
LIB_GMP = ['gmp']
LIB_NTL = ['ntl']
LIB_ST = '-l%s'
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINKFLAGS_cxxshlib = ['-shared']
LINKFLAGS_cxxstlib = ['-Wl,-Bstatic']
LINK_CC = ['/usr/bin/gcc']
LINK_CXX = ['/usr/bin/g++']
LOCALEDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/share/locale'
LOCALSTATEDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/var'
MANDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/share/man'
OLDINCLUDEDIR = '/usr/include'
PACKAGE = []
PDFDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/share/doc/'
PREFIX = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace'
PSDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/share/doc/'
RPATH_ST = '-Wl,-rpath,%s'
SBINDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/sbin'
SHAREDSTATEDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/com'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
SYSCONFDIR = '/u/thiongam/Documents/mamadou2022/workspaceCPP/ProjetLaticeTester/Lattice-Tester/InstallPlace/etc'
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.so'
cstlib_PATTERN = 'lib%s.a'
cxxprogram_PATTERN = '%s'
cxxshlib_PATTERN = 'lib%s.so'
cxxstlib_PATTERN = 'lib%s.a'
define_key = ['HAVE_NTL_VECTOR_H', 'HAVE_GMP_H', 'LATTICETESTER_VERSION']
macbundle_PATTERN = '%s.bundle'
