#!/usr/bin/env python
# coding: utf-8

def build(ctx):
    src_dir = ctx.path.parent.find_dir('progs/')
    #inc_dir = ctx.path.parent.find_dir('analysis/include')
    lat_inc_dir = ctx.path.find_dir('../include')

    ctx(features='cxx cxxprogram',
        source=src_dir.ant_glob('TestLattice.cc'),
        includes=[lat_inc_dir],
        lib=ctx.env.LIB_NTL + ctx.env.LIB_GMP  + ctx.env.LIB_MYLIB,
        stlib=ctx.env.STLIB_NTL + ctx.env.LIB_GMP + ctx.env.STLIB_MYLIB,
        target=('TestLattice'),
        use=['latticetester'],
        install_path='${BINDIR}')
