#!/usr/bin/env python
# coding: utf-8

def build(ctx):
    data_dir = ctx.path

    # data files
    for dat in data_dir.ant_glob('*.dat'):
        ctx.install_files("${PREFIX}/share/latticetester/data", dat)
