#!/usr/bin/env python
# coding: utf-8

import os
from waflib.Build import POST_LAZY

def build(ctx):
    data_dir = ctx.path
    out = ctx.bldnode.abspath()
    ctx.add_group('group_latticetesterdata1')
    ctx.add_group('group_latticetesterdata2')
    ctx.post_mode = POST_LAZY

    # data files
    ctx.set_group('group_latticetesterdata1')
    if ctx.env.BUILD_EXAMPLES:
        if not(os.path.exists(str(out) + '/progs/share/latticetester/data')):
            ctx(rule= 'mkdir -p %s' % str(out) + '/progs/share/latticetester/data', always = True)
    ctx.set_group('group_latticetesterdata2')
    for dat in data_dir.ant_glob('*.dat'):
        if ctx.env.BUILD_EXAMPLES:
            ctx(rule='cp %s %s' %(str(dat), str(out) + '/progs/share/latticetester/data'), always = True)
        ctx.install_files('${PREFIX}/share/latticetester/data', dat)
